// <copyright file="GPGSIds.cs" company="Google Inc.">
// Copyright (C) 2015 Google Inc. All Rights Reserved.
//
//  Licensed under the Apache License, Version 2.0 (the "License");
//  you may not use this file except in compliance with the License.
//  You may obtain a copy of the License at
//
//  http://www.apache.org/licenses/LICENSE-2.0
//
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//    limitations under the License.
// </copyright>

///
/// This file is automatically generated DO NOT EDIT!
///
/// These are the constants defined in the Play Games Console for Game Services
/// Resources.
///

namespace GPGS
{
public static class GPGS
{
        public const string achievement_a = "CgkIg6OK6LkSEAIQBA"; // <GPGSID>
        public const string leaderboard_aa = "CgkIg6OK6LkSEAIQAg"; // <GPGSID>
        public const string achievement_aaaaa = "CgkIg6OK6LkSEAIQBQ"; // <GPGSID>
        public const string achievement_aaa = "CgkIg6OK6LkSEAIQAw"; // <GPGSID>
        public const string achievement_aaaaaza = "CgkIg6OK6LkSEAIQBg"; // <GPGSID>
        public const string achievement_aa = "CgkIg6OK6LkSEAIQAQ"; // <GPGSID>

}
}
